### ISSUE TITLE
Request: Add custom message to the default create/update/delete log entries

### ISSUE THREAD

**Issue by joshualimsm** [elstc/cakephp-activity-logger#10]
I want to add a custom message when updating an Entity. Like this:

```
$this->Articles->setLogMessage( 'Custom Message' );
$article = $this->Articles->patchEntity([ /* ... */ ]);
$this->Articles->save($article);
// saved log
// [action='update', scope_model='Articles', message='Custom Message', ...]
```

If I use `activityLog()` it is difficult to match it to the update log entry.

**Comment by nojimage** [comment]
it's nice idea.
I will try to implement this feature, as soon as possible.

**Comment by nojimage** [comment]
@joshualimsm I implement it #11, please comment if you have a better implementation idea.

**Comment by nojimage** [comment]
See also: https://github.com/elstc/cakephp-activity-logger#activity-logging-with-message

thanks.
