### ISSUE TITLE
Handle logging entity association changes

### ISSUE THREAD

**Issue by jadelbe418** [elstc/cakephp-activity-logger#9]
Not sure if this exists and could be documented, or if this is feature request. But it would be nice to be able to have some way to logging changes of associated entities. For instance I have a task entity with a foreign key that points to another table with a specific priority level. The package currently logs the changed key, but it would be nice to be able to set it to log other values from the associated entity, such as a priority's name, description, etc. so a user without access to the database could understand what the changed in key means.

**Comment by nojimage** [comment]
How about re-linking related data when displaying the log?
However, this method cannot reproduce the state of related data at the time of recording.

The current plugin requires that the `dirty` mark be set for related fields to save related data when logging.

eg: Posts belongsTo Users, `$post->user` is a User entity.

```php
// before save
if ($post->user_id && $post->user === null) {
    // The data that you want to associate and logging must be linked to the entity.
    $post->user = $this->Users->get($post->user_id);
}
$post->setDirty('user', true);
```
